from enum import Enum

class FarmerState(str, Enum):
    MAIN_MENU = "MAIN_MENU"
    AWAITING_QUERY = "AWAITING_QUERY"
    AWAITING_IMAGE = "AWAITING_IMAGE"
    AWAITING_LANGUAGE_CHANGE = "AWAITING_LANGUAGE_CHANGE"
    AWAITING_LOCATION = "AWAITING_LOCATION"
    CONFIRM_LOCATION = "CONFIRM_LOCATION"
    AWAITING_WASTE_CROP = "AWAITING_WASTE_CROP"
    AWAITING_WASTE_QUANTITY = "AWAITING_WASTE_QUANTITY"
    WASTE_CONFIRM_DEAL = "WASTE_CONFIRM_DEAL"
